-- http://luacheck.readthedocs.io/en/stable/warnings.html

std = "lua51"
max_line_length = false
codes = true
exclude_files = {
	"**/Libs",
	".luacheckrc",
	".release",
	"Babelfish.lua",
	"Localization/_export.lua",
}
ignore = {
	"11./SLASH_.*", -- Setting an undefined (Slash handler) global variable
	"11./BINDING_.*", -- Setting an undefined (Keybinding header) global variable
	"113/LE_.*", -- Accessing an undefined (Lua ENUM type) global variable
	"113/NUM_LE_.*", -- Accessing an undefined (Lua ENUM type) global variable
	"211", -- Unused local variable
	"211/L", -- Unused local variable "L"
	"211/CL", -- Unused local variable "CL"
	"212", -- Unused argument
	"213", -- Unused loop variable
	"311", -- Value assigned to a local variable is unused
	"314", -- Value of a field in a table literal is unused
	"42.", -- Shadowing a local variable, an argument, a loop variable.
	"43.", -- Shadowing an upvalue, an upvalue argument, an upvalue loop variable.
	"542", -- An empty if branch
}
globals = {
	-- Third-party
	"LibStub",
	"PitBull4",

	-- Frames/tables/misc
	"ChatFontNormal",
	"CombatFeedbackText",
	"DEFAULT_CHAT_FRAME",
	"Enum",
	"GameTooltip",
	"SOUNDKIT",
	"StaticPopupDialogs",
	"UIErrorsFrame",
	"UIParent",
	"WOW_PROJECT_ID",
	"WOW_PROJECT_CLASSIC",

	-- Functions
	"C_CreatureInfo",
	"C_Timer",
	"CancelItemTempEnchantment",
	"CancelUnitBuff",
	"CastingInfo",
	"ChannelInfo",
	"CheckInteractDistance",
	"CooldownFrame_Set",
	"CopyTable",
	"CreateFrame",
	"DestroyTotem",
	"DisableAddOn",
	"GameTooltip_SetDefaultAnchor",
	"GetAddOnDependencies",
	"GetAddOnEnableState",
	"GetAddOnInfo",
	"GetAddOnMetadata",
	"GetBattlefieldStatus",
	"GetCVarBool",
	"GetComboPoints",
	"GetInventoryItemLink",
	"GetItemInfo",
	"GetItemQualityColor",
	"GetLocale",
	"GetManagedEnvironment",
	"GetMouseFocus",
	"GetNumAddOns",
	"GetNumGroupMembers",
	"GetNumSubgroupMembers",
	"GetPVPTimer",
	"GetPartyAssignment",
	"GetPetExperience",
	"GetPetHappiness",
	"GetQuestDifficultyColor",
	"GetRaidRosterInfo",
	"GetRaidTargetIndex",
	"GetReadyCheckStatus",
	"GetScreenHeight",
	"GetScreenWidth",
	"GetShapeshiftFormID",
	"GetSpellCooldown",
	"GetSpellDescription",
	"GetSpellInfo",
	"GetTime",
	"GetTotemInfo",
	"GetTotemTimeLeft",
	"GetWatchedFactionInfo",
	"GetXPExhaustion",
	"InCombatLockdown",
	"IsAddOnLoadOnDemand",
	"IsAddOnLoaded",
	"IsInGroup",
	"IsInRaid",
	"IsItemInRange",
	"IsPVPTimerRunning",
	"IsPlayerSpell",
	"IsResting",
	"IsShiftKeyDown",
	"IsSpellInRange",
	"IsSpellKnown",
	"LoadAddOn",
	"MainMenuBar_UpdateExperienceBars",
	"PlaySound",
	"PlaySoundFile",
	"RegisterStateDriver",
	"RegisterUnitWatch",
	"SecureHandlerExecute",
	"SecureHandlerSetFrameRef",
	"SetPortraitTexture",
	"ShowBossFrameWhenUninteractable",
	"SpellGetVisibilityInfo",
	"SpellIsSelfBuff",
	"StaticPopup_Show",
	"UnitAffectingCombat",
	"UnitAura",
	"UnitCanAttack",
	"UnitClass",
	"UnitClassBase",
	"UnitClassification",
	"UnitCreatureFamily",
	"UnitCreatureType",
	"UnitDetailedThreatSituation",
	"UnitExists",
	"UnitFactionGroup",
	"UnitGUID",
	"UnitHasIncomingResurrection",
	"UnitHealth",
	"UnitHealthMax",
	"UnitInParty",
	"UnitInPhase",
	"UnitInRaid",
	"UnitInRange",
	"UnitIsAFK",
	"UnitIsConnected",
	"UnitIsDND",
	"UnitIsDead",
	"UnitIsDeadOrGhost",
	"UnitIsEnemy",
	"UnitIsFeignDeath",
	"UnitIsFriend",
	"UnitIsGhost",
	"UnitIsGroupLeader",
	"UnitIsOtherPlayersPet",
	"UnitIsPVP",
	"UnitIsPVPFreeForAll",
	"UnitIsPlayer",
	"UnitIsTapDenied",
	"UnitIsUnit",
	"UnitIsVisible",
	"UnitLevel",
	"UnitName",
	"UnitPlayerControlled",
	"UnitPlayerOrPetInRaid",
	"UnitPower",
	"UnitPowerDisplayMod",
	"UnitPowerMax",
	"UnitPowerType",
	"UnitRace",
	"UnitReaction",
	"UnitSelectionColor",
	"UnitXP",
	"UnitXPMax",
	"UnregisterStateDriver",
	"UnregisterUnitWatch",
	"abs",
	"bit",
	"ceil",
	"date",
	"floor",
	"format",
	"geterrorhandler",
	"hooksecurefunc",
	"math",
	"max",
	"min",
	"string",
	"strsplit",
	"strtrim",
	"table",
	"tremove",
	"tContains",
	"tInvert",
	"wipe",

	-- Strings
	"CANCEL",
	"CAT_FORM",
	"CLASS",
	"CLASS_SORT_ORDER",
	"DAMAGER",
	"DAY_ONELETTER_ABBR",
	"DAYS_ABBR",
	"DECIMAL_SEPERATOR",
	"FIRST_NUMBER_CAP_NO_SPACE",
	"FULL_PLAYER_NAME",
	"HEALER",
	"HOUR_ONELETTER_ABBR",
	"HOURS_ABBR",
	"LARGE_NUMBER_SEPERATOR",
	"LOCALIZED_CLASS_NAMES_MALE",
	"MAX_PARTY_MEMBERS",
	"MAX_RAID_MEMBERS",
	"MINUTE_ONELETTER_ABBR",
	"MINUTES_ABBR",
	"NONE",
	"NUM_BAG_SLOTS",
	"PET_DAMAGE_PERCENTAGE",
	"PET_HAPPINESS1",
	"PET_HAPPINESS2",
	"PET_HAPPINESS3",
	"PET_TYPE_SUFFIX",
	"RAID_CLASS_COLORS",
	"RAID_TARGET_1",
	"RAID_TARGET_2",
	"RAID_TARGET_3",
	"RAID_TARGET_4",
	"RAID_TARGET_5",
	"RAID_TARGET_6",
	"RAID_TARGET_7",
	"RAID_TARGET_8",
	"RELOADUI",
	"SECOND_NUMBER_CAP_NO_SPACE",
	"SECOND_ONELETTER_ABBR",
	"SECONDS_ABBR",
	"TANK",
	"TOOLTIP_BATTLE_PET",
	"UNKNOWN",
}
