name: Package Classic

on:
  push:
    branches:
      - classic
    tags:
      - '**-classic*'
    paths-ignore:
      - '.github/**'


env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout project
      uses: actions/checkout@v1

    - name: Run luacheck
      uses: nebularg/actions-luacheck@v1
      with:
        args: -q

    - name: Package Classic
      uses: BigWigsMods/packager@master
      with:
        args: -g classic

    - name: Package BCC
      uses: BigWigsMods/packager@master
      with:
        args: -g bcc
